import 'eeg_config.dart';
import 'erp_config.dart';

enum PatientConditionCategory {
  normal,
  neurological,
  psychiatric,
  sleep,
  cognitive,
}

class PatientConditionPreset {
  final String id;
  final String title;
  final String category;
  final String medicalDescription;
  final String clinicalSignature;
  final EegConfig eegConfig;
  final ErpConfig erpConfig;

  const PatientConditionPreset({
    required this.id,
    required this.title,
    required this.category,
    required this.medicalDescription,
    required this.clinicalSignature,
    required this.eegConfig,
    required this.erpConfig,
  });
}

final List<PatientConditionPreset> kPatientPresets = [
  PatientConditionPreset(
    id: 'p01',
    title: 'Normal Awake Resting (Eyes Closed)',
    category: 'Healthy Control',
    medicalDescription: 'Healthy baseline with prominent occipital alpha activity during relaxed wakefulness.',
    clinicalSignature: 'Alpha: 10Hz (35uV), Low Beta/Delta.',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 6.0, frequency: 2.0),
      theta: BandConfig(amplitude: 5.0, frequency: 6.0),
      alpha: BandConfig(amplitude: 35.0, frequency: 10.0),
      beta: BandConfig(amplitude: 4.0, frequency: 18.0),
      gamma: BandConfig(amplitude: 1.5, frequency: 35.0),
      noisePercent: 3.0,
      artifacts: ArtifactConfig(),
    ),
    erpConfig: ErpConfig(fixedIsiMs: 1200.0),
  ),
  PatientConditionPreset(
    id: 'p02',
    title: 'Deep Focused State / Meditation',
    category: 'Healthy Control',
    medicalDescription: 'Enhanced fronto-midline theta and baseline alpha coherence observed during intense mental focus.',
    clinicalSignature: 'High Theta & Gamma synchrony.',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 4.0, frequency: 2.5),
      theta: BandConfig(amplitude: 25.0, frequency: 6.5),
      alpha: BandConfig(amplitude: 18.0, frequency: 10.5),
      beta: BandConfig(amplitude: 8.0, frequency: 20.0),
      gamma: BandConfig(amplitude: 12.0, frequency: 40.0),
      noisePercent: 4.0,
      artifacts: ArtifactConfig(),
    ),
    erpConfig: ErpConfig(fixedIsiMs: 1000.0),
  ),
  PatientConditionPreset(
    id: 'p03',
    title: 'Epilepsy - Interictal Spikes',
    category: 'Neurological',
    medicalDescription: 'Intermittent sharp waves and spike-wave complexes in temporal lobes between seizure events.',
    clinicalSignature: 'Elevated noise, abrupt amplitude spikes, EMG artifacts.',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 18.0, frequency: 1.8),
      theta: BandConfig(amplitude: 14.0, frequency: 5.5),
      alpha: BandConfig(amplitude: 8.0, frequency: 9.0),
      beta: BandConfig(amplitude: 15.0, frequency: 24.0),
      gamma: BandConfig(amplitude: 8.0, frequency: 45.0),
      noisePercent: 18.0,
      artifacts: ArtifactConfig(emg: true, eyeBlink: true),
    ),
    erpConfig: ErpConfig(jitterPercent: 20.0),
  ),
  PatientConditionPreset(
    id: 'p04',
    title: 'Absence Seizure (3Hz Spike-Wave)',
    category: 'Neurological',
    medicalDescription: 'Classic generalized 3 Hz spike-and-slow-wave discharges during brief lapses of consciousness.',
    clinicalSignature: 'High-amplitude 3Hz Delta/Theta surges.',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 45.0, frequency: 3.0),
      theta: BandConfig(amplitude: 28.0, frequency: 6.0),
      alpha: BandConfig(amplitude: 4.0, frequency: 9.5),
      beta: BandConfig(amplitude: 3.0, frequency: 16.0),
      gamma: BandConfig(amplitude: 1.0, frequency: 32.0),
      noisePercent: 12.0,
      artifacts: ArtifactConfig(emg: false, eyeBlink: true),
    ),
    erpConfig: ErpConfig(jitterPercent: 25.0),
  ),
  PatientConditionPreset(
    id: 'p05',
    title: 'Alzheimer\'s Disease (Mild Cognitive Impairment)',
    category: 'Cognitive & Neurodegenerative',
    medicalDescription: 'EEG slowing with reduced alpha power and elevated diffuse theta/delta rhythms.',
    clinicalSignature: 'Marked Alpha suppression, Theta elevation (18uV).',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 16.0, frequency: 2.0),
      theta: BandConfig(amplitude: 24.0, frequency: 5.0),
      alpha: BandConfig(amplitude: 8.0, frequency: 8.5),
      beta: BandConfig(amplitude: 4.0, frequency: 15.0),
      gamma: BandConfig(amplitude: 1.5, frequency: 30.0),
      noisePercent: 8.0,
      artifacts: ArtifactConfig(eyeBlink: true),
    ),
    erpConfig: ErpConfig(p300: ErpComponentConfig(name: 'P300', latencyMs: 380.0, amplitudeUv: 3.0, sigmaMs: 40.0)),
  ),
  PatientConditionPreset(
    id: 'p06',
    title: 'Major Depressive Disorder (Alpha Asymmetry)',
    category: 'Psychiatric',
    medicalDescription: 'Frontal alpha asymmetry with hypo-activation in left frontal cortical regions.',
    clinicalSignature: 'High Frontal Alpha (26uV), Reduced Beta.',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 8.0, frequency: 2.0),
      theta: BandConfig(amplitude: 12.0, frequency: 5.8),
      alpha: BandConfig(amplitude: 26.0, frequency: 9.8),
      beta: BandConfig(amplitude: 5.0, frequency: 17.0),
      gamma: BandConfig(amplitude: 2.0, frequency: 32.0),
      noisePercent: 6.0,
      artifacts: ArtifactConfig(),
    ),
    erpConfig: ErpConfig(fixedIsiMs: 1400.0),
  ),
  PatientConditionPreset(
    id: 'p07',
    title: 'ADHD (Elevated Theta/Beta Ratio)',
    category: 'Cognitive & Neurodegenerative',
    medicalDescription: 'High theta-to-beta ratio (TBR > 4.5) indicative of cortical under-arousal in frontal lobes.',
    clinicalSignature: 'Theta: 28uV, Beta: 4uV (High TBR).',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 10.0, frequency: 2.2),
      theta: BandConfig(amplitude: 28.0, frequency: 5.5),
      alpha: BandConfig(amplitude: 12.0, frequency: 10.0),
      beta: BandConfig(amplitude: 4.0, frequency: 16.0),
      gamma: BandConfig(amplitude: 2.0, frequency: 35.0),
      noisePercent: 9.0,
      artifacts: ArtifactConfig(eyeBlink: true, emg: true),
    ),
    erpConfig: ErpConfig(p300: ErpComponentConfig(name: 'P300', latencyMs: 350.0, amplitudeUv: 4.0, sigmaMs: 35.0)),
  ),
  PatientConditionPreset(
    id: 'p08',
    title: 'Generalized Anxiety (Hyper-Beta Activity)',
    category: 'Psychiatric',
    medicalDescription: 'Pervasive high-frequency beta and gamma activity reflecting persistent cortical hyper-arousal.',
    clinicalSignature: 'Elevated Beta (26uV) & Gamma (10uV).',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 4.0, frequency: 2.5),
      theta: BandConfig(amplitude: 6.0, frequency: 6.0),
      alpha: BandConfig(amplitude: 9.0, frequency: 10.5),
      beta: BandConfig(amplitude: 26.0, frequency: 25.0),
      gamma: BandConfig(amplitude: 10.0, frequency: 42.0),
      noisePercent: 11.0,
      artifacts: ArtifactConfig(emg: true),
    ),
    erpConfig: ErpConfig(fixedIsiMs: 900.0),
  ),
  PatientConditionPreset(
    id: 'p09',
    title: 'Severe Parkinson\'s Disease',
    category: 'Neurological',
    medicalDescription: 'Increased beta band burst oscillations along with resting motor tremor artifacts (4-6Hz).',
    clinicalSignature: 'Beta synchronized bursts, High EMG/Tremor noise.',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 14.0, frequency: 1.8),
      theta: BandConfig(amplitude: 16.0, frequency: 5.0),
      alpha: BandConfig(amplitude: 11.0, frequency: 9.0),
      beta: BandConfig(amplitude: 20.0, frequency: 21.0),
      gamma: BandConfig(amplitude: 3.0, frequency: 36.0),
      noisePercent: 16.0,
      artifacts: ArtifactConfig(emg: true),
    ),
    erpConfig: ErpConfig(jitterPercent: 15.0),
  ),
  PatientConditionPreset(
    id: 'p10',
    title: 'Traumatic Brain Injury (Focal Slow Wave)',
    category: 'Neurological',
    medicalDescription: 'Focal delta and theta slowing in damaged cerebral parenchyma with impaired sensory evoked potentials.',
    clinicalSignature: 'Dominant slow Delta (22uV), Low Alpha.',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 22.0, frequency: 1.5),
      theta: BandConfig(amplitude: 18.0, frequency: 4.5),
      alpha: BandConfig(amplitude: 7.0, frequency: 8.8),
      beta: BandConfig(amplitude: 5.0, frequency: 15.0),
      gamma: BandConfig(amplitude: 1.0, frequency: 30.0),
      noisePercent: 10.0,
      artifacts: ArtifactConfig(eyeBlink: true),
    ),
    erpConfig: ErpConfig(p300: ErpComponentConfig(name: 'P300', latencyMs: 390.0, amplitudeUv: 2.5, sigmaMs: 45.0)),
  ),
  PatientConditionPreset(
    id: 'p11',
    title: 'Stage N3 Sleep (Slow-Wave Delta Sleep)',
    category: 'Sleep Architecture',
    medicalDescription: 'Dominant high-voltage delta waves (>75uV, 0.5-2Hz) occupying more than 20% of sleep epoch.',
    clinicalSignature: 'High Voltage Delta (50uV), Low Beta/Gamma.',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 50.0, frequency: 1.2),
      theta: BandConfig(amplitude: 10.0, frequency: 4.0),
      alpha: BandConfig(amplitude: 3.0, frequency: 8.5),
      beta: BandConfig(amplitude: 1.5, frequency: 14.0),
      gamma: BandConfig(amplitude: 0.5, frequency: 30.0),
      noisePercent: 4.0,
      artifacts: ArtifactConfig(),
    ),
    erpConfig: ErpConfig(fixedIsiMs: 2000.0),
  ),
  PatientConditionPreset(
    id: 'p12',
    title: 'REM Sleep (Rapid Eye Movement)',
    category: 'Sleep Architecture',
    medicalDescription: 'Low-voltage mixed frequency EEG resembling wakefulness with rapid eye movement muscle artifacts.',
    clinicalSignature: 'Sawtooth Theta waves, Ocular EMG bursts.',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 8.0, frequency: 2.5),
      theta: BandConfig(amplitude: 18.0, frequency: 6.0),
      alpha: BandConfig(amplitude: 9.0, frequency: 9.5),
      beta: BandConfig(amplitude: 12.0, frequency: 22.0),
      gamma: BandConfig(amplitude: 4.0, frequency: 38.0),
      noisePercent: 12.0,
      artifacts: ArtifactConfig(eyeBlink: true, emg: true),
    ),
    erpConfig: ErpConfig(jitterPercent: 18.0),
  ),
  PatientConditionPreset(
    id: 'p13',
    title: 'Acute Ischemic Stroke (Polymorphic Delta)',
    category: 'Neurological',
    medicalDescription: 'Continuous polymorphic delta activity (PIRDA) over infarcted vascular territory.',
    clinicalSignature: 'High Polymorphic Delta (32uV), Absent Alpha.',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 32.0, frequency: 1.2),
      theta: BandConfig(amplitude: 15.0, frequency: 4.8),
      alpha: BandConfig(amplitude: 3.0, frequency: 8.0),
      beta: BandConfig(amplitude: 2.0, frequency: 14.0),
      gamma: BandConfig(amplitude: 0.8, frequency: 28.0),
      noisePercent: 14.0,
      artifacts: ArtifactConfig(emg: true),
    ),
    erpConfig: ErpConfig(jitterPercent: 30.0),
  ),
  PatientConditionPreset(
    id: 'p14',
    title: 'Schizophrenia (Reduced Gamma Oscillations)',
    category: 'Psychiatric',
    medicalDescription: 'Deficits in parvalbumin interneuron-mediated gamma auditory steady-state response (ASSR).',
    clinicalSignature: 'Suppressed Gamma (1uV), Fragmented Alpha.',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 12.0, frequency: 2.0),
      theta: BandConfig(amplitude: 16.0, frequency: 5.5),
      alpha: BandConfig(amplitude: 8.0, frequency: 9.2),
      beta: BandConfig(amplitude: 7.0, frequency: 18.0),
      gamma: BandConfig(amplitude: 1.0, frequency: 40.0),
      noisePercent: 9.0,
      artifacts: ArtifactConfig(eyeBlink: true),
    ),
    erpConfig: ErpConfig(p300: ErpComponentConfig(name: 'P300', latencyMs: 360.0, amplitudeUv: 2.8, sigmaMs: 38.0)),
  ),
  PatientConditionPreset(
    id: 'p15',
    title: 'Severe Mental Fatigue / Burnout',
    category: 'Cognitive & Neurodegenerative',
    medicalDescription: 'Prolonged cognitive task execution leading to continuous delta/theta power accumulation.',
    clinicalSignature: 'Elevated Theta (24uV), Slowed Alpha.',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 18.0, frequency: 1.8),
      theta: BandConfig(amplitude: 24.0, frequency: 5.8),
      alpha: BandConfig(amplitude: 10.0, frequency: 9.0),
      beta: BandConfig(amplitude: 5.0, frequency: 16.0),
      gamma: BandConfig(amplitude: 1.5, frequency: 32.0),
      noisePercent: 8.0,
      artifacts: ArtifactConfig(eyeBlink: true),
    ),
    erpConfig: ErpConfig(fixedIsiMs: 1500.0),
  ),
  PatientConditionPreset(
    id: 'p16',
    title: 'Propofol Sedation (Frontal Alpha Hypersynchrony)',
    category: 'Neurological',
    medicalDescription: 'Coherent frontal alpha-slow oscillations induced by GABA-A receptor potentiation.',
    clinicalSignature: 'High Coherent Alpha (38uV) & Delta (25uV).',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 25.0, frequency: 1.5),
      theta: BandConfig(amplitude: 12.0, frequency: 5.0),
      alpha: BandConfig(amplitude: 38.0, frequency: 11.0),
      beta: BandConfig(amplitude: 3.0, frequency: 15.0),
      gamma: BandConfig(amplitude: 0.5, frequency: 30.0),
      noisePercent: 3.0,
      artifacts: ArtifactConfig(),
    ),
    erpConfig: ErpConfig(fixedIsiMs: 1800.0),
  ),
  PatientConditionPreset(
    id: 'p17',
    title: 'Migraine Aura (Cortical Spreading Depression)',
    category: 'Neurological',
    medicalDescription: 'Transient cortical hyperexcitability followed by sustained depression of electrical activity.',
    clinicalSignature: 'Fluctuating High Beta/Gamma to Low Voltage.',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 9.0, frequency: 2.0),
      theta: BandConfig(amplitude: 11.0, frequency: 6.2),
      alpha: BandConfig(amplitude: 14.0, frequency: 10.2),
      beta: BandConfig(amplitude: 22.0, frequency: 26.0),
      gamma: BandConfig(amplitude: 14.0, frequency: 45.0),
      noisePercent: 11.0,
      artifacts: ArtifactConfig(eyeBlink: true),
    ),
    erpConfig: ErpConfig(jitterPercent: 12.0),
  ),
  PatientConditionPreset(
    id: 'p18',
    title: 'Chronic Insomnia (Nocturnal Hyper-Arousal)',
    category: 'Sleep Architecture',
    medicalDescription: 'High fast-frequency beta (14-30Hz) during sleep onset transitions reflecting central hyper-arousal.',
    clinicalSignature: 'Persistently high Beta (20uV) during rest.',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 6.0, frequency: 2.2),
      theta: BandConfig(amplitude: 7.0, frequency: 6.0),
      alpha: BandConfig(amplitude: 12.0, frequency: 10.0),
      beta: BandConfig(amplitude: 20.0, frequency: 23.0),
      gamma: BandConfig(amplitude: 6.0, frequency: 38.0),
      noisePercent: 7.0,
      artifacts: ArtifactConfig(eyeBlink: true),
    ),
    erpConfig: ErpConfig(fixedIsiMs: 1100.0),
  ),
  PatientConditionPreset(
    id: 'p19',
    title: 'Hepatic Encephalopathy (Triphasic Waves)',
    category: 'Neurological',
    medicalDescription: 'Generalized periodic triphasic waves with anterior-to-posterior time lag secondary to metabolic dysfunction.',
    clinicalSignature: 'Triphasic Slow Delta/Theta Surges (30uV).',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 30.0, frequency: 1.8),
      theta: BandConfig(amplitude: 22.0, frequency: 4.8),
      alpha: BandConfig(amplitude: 4.0, frequency: 8.0),
      beta: BandConfig(amplitude: 4.0, frequency: 14.0),
      gamma: BandConfig(amplitude: 0.5, frequency: 30.0),
      noisePercent: 10.0,
      artifacts: ArtifactConfig(emg: true),
    ),
    erpConfig: ErpConfig(jitterPercent: 22.0),
  ),
  PatientConditionPreset(
    id: 'p20',
    title: 'Essential Tremor (Action Tremor Artifacts)',
    category: 'Neurological',
    medicalDescription: 'Rhythmic 4-12 Hz muscle contractions superimposed on normal background cortical rhythms.',
    clinicalSignature: 'High EMG Artifacts, Normal Alpha/Beta.',
    eegConfig: EegConfig(
      delta: BandConfig(amplitude: 6.0, frequency: 2.0),
      theta: BandConfig(amplitude: 8.0, frequency: 6.0),
      alpha: BandConfig(amplitude: 18.0, frequency: 10.0),
      beta: BandConfig(amplitude: 10.0, frequency: 19.0),
      gamma: BandConfig(amplitude: 3.0, frequency: 35.0),
      noisePercent: 20.0,
      artifacts: ArtifactConfig(emg: true),
    ),
    erpConfig: ErpConfig(fixedIsiMs: 1000.0),
  ),
];